name: mhchem_parser
description: Parser for mhchem chemical equation notation. Converts \ce and \pu syntax to LaTeX.
version: 4.2.2
homepage: https://github.com/mhchem/mhchemParser

environment:
  sdk: '>=2.17.0 <3.0.0'

dev_dependencies:
  test: ^1.21.0
